apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: time-to-failure
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: preprocess
        template: preprocess
      - name: train
        dependencies: [preprocess]
        template: train
  # Docker Images
  - name: preprocess
    container:
      image: us-central1-docker.pkg.dev/data-science-362714/data-science/time-to-failure-preprocess:1.0
  - name: train
    container:
      image: us-central1-docker.pkg.dev/data-science-362714/data-science/time-to-failure-train:1.0