apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "jupyterlab"
  namespace: "jlab"
  labels:
    app: "jupyterlab"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "jupyterlab"
  template:
    metadata:
      labels:
        app: "jupyterlab"
    spec:
      containers:
      - name: "jupyter-1"
        image: "us-central1-docker.pkg.dev/data-science-362714/time-to-failure/jupyter:1.0"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "jupyterlab-hpa-etya"
  namespace: "jlab"
  labels:
    app: "jupyterlab"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "jupyterlab"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80